master:
  enabled: true

filer:
  enabled: true
  s3:
    enabled: true

volume:
  enabled: true

  nodeSets:
  - name: hdd
    replicas: 1
    args:
      rack: hdd-rack

    persistence:
      enabled: true
      disks:
      - disk: hdd
        max: 0
        existingClaim: ""
        storageClass: ""
        accessModes:
          - ReadWriteOnce
        size: 50Gi

# You may specify buckets with ttl policy to be created during the install process
#s3:
#  createBuckets:
#  - name: bucket-a
#    ttl: 1d
#  - name: bucket-b
