{{- if and (.Values.filer.enabled) (.Values.filer.config) (not .Values.filer.existingConfigSecret) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "seaweedfs.name" . }}-filer-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "seaweedfs.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
stringData:
  filer.toml: |-
    {{- .Values.filer.config | nindent 4 }}
{{- end }}
