{{- if and .Values.server.enabled .Values.server.filer.enabled .Values.server.filer.config }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "seaweedfs.name" . }}-server-filer-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "seaweedfs.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
stringData:
  filer.toml: |-
    {{- .Values.server.filer.config | nindent 4 }}
{{- end }}
