{{- if .Values.filer.enabled }}
{{- if .Values.filer.ingress.enabled }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: ingress-{{ template "seaweedfs.name" . }}-filer
  namespace: {{ .Release.Namespace }}
  {{- with .Values.filer.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "seaweedfs.labels" . | nindent 4 }}
    app.kubernetes.io/component: filer
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.filer.ingress.className | quote }}
  tls:
    {{- .Values.filer.ingress.tls | default list | toYaml | nindent 4 }}
  rules:
  - http:
      paths:
      - path: /sw-filer/?(.*)
        pathType: ImplementationSpecific
        backend:
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
          service:
            name: {{ template "seaweedfs.name" . }}-filer
            port:
              number: 8888
{{- else }}
          serviceName: {{ template "seaweedfs.name" . }}-filer
          servicePort: 8888
{{- end }}
{{- if .Values.filer.ingress.host }}
    host: {{ .Values.filer.ingress.host }}
{{- end }}
{{- end }}
{{- end }}
