{{- if or (and .Values.s3.enabled .Values.s3.auth.enabled (not .Values.s3.auth.existingConfigSecret)) (and .Values.filer.enabled .Values.filer.s3.enabled .Values.filer.s3.auth.enabled (not .Values.filer.s3.auth.existingConfigSecret)) (and .Values.server.enabled .Values.server.s3.enabled .Values.server.s3.auth.enabled (not .Values.server.s3.auth.existingConfigSecret)) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "seaweedfs.name" . }}-s3-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
    "helm.sh/hook": "pre-install"
  labels:
    {{- include "seaweedfs.labels" . | nindent 4 }}
    app.kubernetes.io/component: s3
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
stringData:
  config.json: |
    {{- $config := "" }}

    {{- if .Values.s3.enabled }}
      {{- $config = .Values.s3.auth.config | fromYaml }}
    {{- else if and .Values.filer.enabled .Values.filer.s3.enabled }}
      {{- $config = .Values.filer.s3.auth.config | fromYaml }}
    {{- else if and .Values.server.enabled .Values.server.s3.enabled }}
      {{- $config = .Values.server.s3.auth.config | fromYaml }}
    {{- end }}
    {{- $processedIdentities := list }}
    {{- range $index, $identity := $config.identities }}
      {{- $name := $identity.name }}
      {{- $actions := $identity.actions }}
      {{- $credentials := $identity.credentials }}     
      {{- $newIdentity := dict }}

      {{- if $credentials }}
        {{- $accessKey := default (randAlphaNum 16) $credentials.accessKey }}
        {{- $secretKey := default (randAlphaNum 32) $credentials.secretKey }}
        {{- $newCredentials := dict "accessKey" $accessKey "secretKey" $secretKey }}
        {{- $newIdentity = dict "name" $name "credentials" $newCredentials "actions" $actions }}
      {{- else }}
        {{- $newIdentity = dict "name" $name "actions" $actions }}
      {{- end }}

      {{- $processedIdentities = append $processedIdentities $newIdentity }}
    {{- end }}

    {{- dict "identities" $processedIdentities | toJson | nindent 4 }}
  {{- if .Values.filer.s3.auth.auditLogConfig }}
  filer_auditLogConfig.json: |
    {{ toJson .Values.filer.s3.auth.auditLogConfig | nindent 4 }}
  {{- end }}
  {{- if .Values.s3.auth.auditLogConfig }}
  auditLogConfig.json: |
    {{ toJson .Values.s3.auth.auditLogConfig | nindent 4 }}
  {{- end }}
{{- end }}
