{{- if or .Values.s3.enabled (and .Values.filer.enabled .Values.filer.s3.enabled) (and .Values.server.enabled .Values.server.s3.enabled) }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ template "seaweedfs.name" . }}-s3
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "seaweedfs.labels" . | nindent 4 }}
    app.kubernetes.io/component: s3
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  internalTrafficPolicy: {{ coalesce (ternary .Values.s3.internalTrafficPolicy "" .Values.s3.enabled) (ternary .Values.filer.s3.internalTrafficPolicy "" (and .Values.filer.enabled .Values.filer.s3.enabled)) (ternary .Values.server.s3.internalTrafficPolicy "" (and .Values.server.enabled .Values.server.s3.enabled)) | default "Cluster" }}
  ports:
  - name: "swfs-s3"
    port: 8333
    targetPort: 8333
    protocol: TCP
  - name: "swfs-s3-grpc"
    port: 18333
    targetPort: 18333
    protocol: TCP
  {{- $onlyHttps := (coalesce (ternary .Values.s3.onlyHttps "" .Values.s3.enabled) (ternary .Values.filer.s3.onlyHttps "" (and .Values.filer.enabled .Values.filer.s3.enabled)) (ternary .Values.server.s3.onlyHttps "" (and .Values.server.enabled .Values.server.s3.enabled)) | default "") }}
  {{- if and .Values.security.enabled .Values.security.tls.enabled (not $onlyHttps) }}
  - name: "swfs-s3-tls"
    port: 18443
    targetPort: 18443
    protocol: TCP
  {{- end }}
  {{- if and .Values.s3.enabled .Values.metrics.enabled }}
  - name: "metrics"
    port: 9327
    targetPort: 9327
    protocol: TCP
  {{- end }}
  selector:
    {{- include "seaweedfs.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ if .Values.s3.enabled }}s3{{ else }}{{ if and .Values.server.enabled (not .Values.filer.enabled) }}server{{ else }}filer{{ end }}{{ end }}
{{- end }}
