{{- if and .Values.server.enabled .Values.server.master.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "seaweedfs.name" . }}-server-master-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "seaweedfs.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  master.toml: |-
    {{- .Values.server.master.config | nindent 4 }}
{{- end }}
