{{- if .Values.iam.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "seaweedfs.name" . }}-iam
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/resource-policy": keep
  labels:
    {{- include "seaweedfs.labels" . | nindent 4 }}
    app.kubernetes.io/component: s3
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
stringData:
  admin-username: {{ .Values.iam.admin.username }}
  admin-password: {{ .Values.iam.admin.password | default (randAlphaNum 16) }}
{{- end }}
