{{- if and .Values.security.enabled }}
{{- if and .Values.security.tls.enabled (not .Values.security.tls.externalCertificates.enabled) }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "seaweedfs.name" . }}-ca-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "seaweedfs.labels" . | nindent 4 }}
spec:
  secretName: {{ template "seaweedfs.name" . }}-ca-cert
  commonName: "{{ template "seaweedfs.name" . }}-root-ca"
  isCA: true
  issuerRef:
    name: {{ template "seaweedfs.name" . }}-issuer
    kind: Issuer
{{- end }}
{{- end }}
